name: SSE automation workflow

on: [push]

jobs:
  style:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: "Install the style checker using pip"
        run: pip install black
      - name: "Run a style check using black utility"
        run: black --check .